site_name: geoSiteYamaguchi

use_directory_urls: 140.227.176.133

theme:
  language: ja
  name: bootswatch

nav:
- Home: 'index.md'

- Documentation:
  - geodjango: 'geodjango.md'
  - infra: 'infra.md'
  - お問い合わせ: 'about.md'




