site_name: 地図サイトを作ってみる
site_url: http://140.227.176.133

theme:
  language: ja
  name: minty
  nav_style: dark

nav:
- サイト説明: 'index.md'
- Django設定: 'geodjango.md'
- インフラ: 'infra.md'
- お問い合わせ: 'about.md'